#################################################################
#								#
# Copyright (c) 2019-2023 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################
# This file mirrors the pipeline set-up, but is not used by the
# pipeline. It lets you run the pipeline tests locally.
#
# Insturctions:
# docker run --rm --name mysql -e MYSQL_ROOT_PASSWORD=ydbrocks -d mysql:8.0 OR docker run --rm --name mysql -e MARIADB_ROOT_PASSWORD=ydbrocks -d mariadb
# docker build -f tools/misc-dockerfiles/Dockerfile-Tests.ubuntu -t tests-ubuntu .
# docker run -it --link mysql --rm tests-ubuntu
# OR docker run -it --link mysql --rm tests-ubuntu "test-auto-upgrade" "debug" "52ba5a43" "test_display_relation_commands"
# OR docker run -it --link mysql --rm tests-ubuntu "test-auto-upgrade" "debug" "52ba5a43" "ALL" (to run all auto-upgrade tests for a specific commit)
# OR docker run -it --link mysql -v /tmp/myfolder:/octooutput --rm tests-ubuntu "test-auto-upgrade" "debug" "52ba5a43" "ALL" (keeps the tests output in /tmp/myfolder so that it can be examined)
# docker kill mysql; docker rm mysql

FROM registry.gitlab.com/yottadb/dbms/ydbocto:ubuntu-master
ADD . /builds/YDBDBMS/
WORKDIR /builds/YDBDBMS
ENTRYPOINT ["tools/ci/build.sh"]
CMD ["make-ubuntu", "none"]
