#################################################################
#								#
# Copyright (c) 2023-2024 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################
ARG imagetag=latest-master
FROM yottadb/yottadb-rocky-base:${imagetag}
RUN ln -fs /usr/share/zoneinfo/US/Eastern /etc/localtime

# Yum update and packages
RUN yum update -y  && \
    yum clean all && \
    rm -rf /var/cache/yum/* && \
    yum --enablerepo=powertools install -y libcmocka-devel gcc libasan make clang clang-tools-extra cmake bison flex python3 python3-pip readline-devel git libconfig-devel openssl-devel postgresql postgresql-server libgcrypt-devel gpgme-devel openssl expect java-11-openjdk-devel tzdata-java unzip unixODBC postgresql-odbc diffutils pkg-config libicu-devel glibc-langpack-en wget mysql-server mysql xz curl go nmap-ncat epel-release postgresql-devel && \
    # we need to enable epel-release first before installing R
    # also need to enable powertools repo to install some dependencies for R
    yum --enablerepo=powertools install -y R

# Ninja
RUN wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip && unzip ninja-linux.zip && mv ninja /usr/local/bin/ninja

# Shellcheck
RUN curl -LOf https://github.com/koalaman/shellcheck/releases/download/v0.7.2/shellcheck-v0.7.2.linux.x86_64.tar.xz && tar -C /usr/local/bin/ -xf shellcheck-v0.7.2.linux.x86_64.tar.xz --no-anchored 'shellcheck' --strip=1
ENV USER=root
