#################################################################
#								#
# Copyright (c) 2023-2026 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################
ARG imagetag=latest-master
FROM yottadb/yottadb-rocky-base:${imagetag}
RUN ln -fs /usr/share/zoneinfo/US/Eastern /etc/localtime

# Yum update and packages
RUN yum update -y  && \
    yum clean all && \
    rm -rf /var/cache/yum/*
# Next line makes bats and R packages available
RUN yum install -y epel-release
# Note: following line is taken verbatim from developer_doc.rst
RUN yum --enablerepo=crb install -y bats R clang-tools-extra java-11-openjdk-devel expect golang glibc-langpack-en libcmocka-devel postgresql postgresql-server unixODBC postgresql-odbc bison flex readline-devel libconfig-devel openssl-devel python3 passwd nmap-ncat iproute postgresql-devel libomp-devel libtirpc-devel
# Note: "openssl" is deliberately not listed below. It comes with the base image, and naming an
# already installed package makes yum ask for the newest version of it rather than for the version
# that the rest of the transaction can satisfy.
RUN yum --enablerepo=crb install -y gcc libasan make clang cmake python3-pip git libgcrypt-devel gpgme-devel java-11-openjdk-devel tzdata-java unzip diffutils pkg-config libicu-devel wget xz

# Ninja
RUN wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip && unzip ninja-linux.zip && mv ninja /usr/local/bin/ninja

# Shellcheck
RUN curl -LOf https://github.com/koalaman/shellcheck/releases/download/v0.7.2/shellcheck-v0.7.2.linux.x86_64.tar.xz && tar -C /usr/local/bin/ -xf shellcheck-v0.7.2.linux.x86_64.tar.xz --no-anchored 'shellcheck' --strip=1

# R packages used by the "r_connection" test. The Posit repository serves prebuilt binaries for this
# distribution, and R asks for them only when the HTTP User-Agent names the platform. The "library"
# call that follows fails the build if the install did not produce a usable package.
RUN . /etc/os-release && \
    Rscript -e "repo <- 'https://packagemanager.posit.co/cran/__linux__/rhel${VERSION_ID%%.*}/latest'; options(HTTPUserAgent=sprintf('R/%s R (%s)', getRversion(), paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']))); install.packages(c('RJDBC','RPostgres'), repos=repo)" && \
    Rscript -e 'library(RJDBC); library(RPostgres)'

ENV USER=root
