#!/usr/bin/expect
#################################################################
#								#
# Copyright (c) 2019 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

set timeout 2
set port [lindex $argv 0];
spawn /bin/bash
# Enable long lines to prevent wrapping
send -- "stty cols 4096\r"
expect "stty cols 4096\r"
# Start psql
send -- "psql -U ydb -h localhost -p $port\r"
expect ".*Password for user ydb: "
send "ydbrocks\r"
expect ".*ydb=# "
# Run a long time AND generate cross references
send "select n1.id from names as n1 left join names as n2 on n1.id != n2.id left join names as n3 on n1.id != n3.id left join names as n4 on n1.id != n4.id left join names as n5 on n1.id != n5.id left join names as n6 on n1.id != n6.id left join names as n7 on n1.id != n7.id;\r"
expect "select n1.id from names as n1 left join names as n2 on n1.id != n2.id left join names as n3 on n1.id != n3.id left join names as n4 on n1.id != n4.id left join names as n5 on n1.id != n5.id left join names as n6 on n1.id != n6.id left join names as n7 on n1.id != n7.id;\r\n"
expect timeout
# Send interrupt to trigger cancel request
send \x03
expect ".*Cancel request sent\r\n"
expect "ERROR:  canceling statement due to user request\r\nydb=# "
send "\\q\r"
expect timeout
exit
