#!/usr/bin/expect
#################################################################
#								#
# Copyright (c) 2019-2023 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

# set huge timeout since on a loaded system it is possible the psql password prompt takes some time to show up
set timeout 60
set port [lindex $argv 0];

# Start bash with --noprofile as otherwise SUSE /etc/profile blindly overwrites $PATH causing below "octo" invocations to fail
spawn /bin/bash --noprofile

# Enable long lines to prevent wrapping
send -- "stty cols 4096\r"
expect "stty cols 4096\r"
# Start psql
send -- "psql -U ydb -h localhost -p $port\r"
expect -re ".*Password for user ydb: "
send "ydbrocks\r"
expect -re ".*ydb=. "
# Run a long time AND generate cross references
send "select n1.id,n2.id from names n1, names n2 WHERE HANGTIME('Zero',5) = n1.firstname;\r"
# get back to small timeout since we want the below to timeout so we can continue with canceling the query
set timeout 2
expect timeout
# Send interrupt to trigger cancel request
send \x03
expect -re ".*Cancel request sent\r\n"
expect -re "ERROR:  canceling statement due to user request\r\nydb=. "
puts "# OCTO645 : Test that a valid short query works fine after a canceled query (it used to be incorrectly treated as canceled)"
send "select * from names;\r"
expect -re "ydb=. "
send "\\q\r"
expect -re "\[#\$] "
exit
