#################################################################
#								#
# Copyright (c) 2023 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

create table test1 (id int generated by default as identity, name text);
create table test2 (name text, id int generated always as identity);
create table test3 (name text, id int generated by default as identity check (id<3));
create table test4 (name text, id int generated always as identity constraint constr_name check (id<3));
update test4 set id = default; -- This query is used to verify that DEFAULT is seen in Octo log
insert into test3 overriding user value values('first',1); -- Do not expect to see OVERRIDING USER VALUE in insert logical plan
insert into test4(name) overriding system value values('first'); -- Do not expect to see OVERRIDING SYSTEM VALUE in insert logical plan
