
#################################################################
#								#
# Copyright (c) 2021-2023 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

-- Basic test for implicit null constraint addition to identity columns
create table test (id integer generated always as identity, name text);
insert into test overriding system value values(NULL, 'first'); -- ERR_NULL_COL_VALUE
insert into test overriding system value values(34, 'first'); -- valid
insert into test overriding user value values(NULL, 'first'); -- ERR_INSERT_ON_GENERATED_ALWAYS_IDENTITY
select * from test;
drop table test;
create table test (id int generated by default as identity, name text);
insert into test values(NULL, 'first');
insert into test values(23, 'first');
insert into test overriding user value values(NULL, 'first'); -- valid case as NULL is replaced by auto-increment value
insert into test overriding system value values(NULL, 'first'); -- ERR_NULL_COL_VALUE
select * from test;
drop table test;

create table test (id integer generated always as identity, name text);
insert into test(name) values('first'),('second');
update test set id=NULL; -- only default allowed
update test set id=NULL where name='first'; -- only default allowed
drop table test;
create table test(id integer generated by default as identity, name text);
insert into test(name) values('first'),('second');
update test set id=NULL; -- ERR_NULL_COL_VALUE
update test set id=NULL where name='first'; -- ERR_NULL_COL_VALUE
drop table test;

-- Test case where insert fails due to NULL CONSTRAINT VIOLATION and the auto-increment value is rolled back
create table test (id integer generated always as identity, name text);
insert into test(name) values('first'),('second'); -- valid query, ids for the rows inserted here will be 1 and 2
insert into test overriding system value values(NULL, 'third'); -- ERR_NULL_COL_VALUE
insert into test overriding user value values(NULL, 'third'); -- ERR_INSERT_ON_GENERATED_ALWAYS_IDENTITY
insert into test (name) values('fourth'); -- id for this row will be 3
select * from test;
drop table test;
create table test (id integer generated by default as identity, name text);
insert into test(name) values('first'),('second'); -- valid query ids for the rows inserted here will be 1 and 2
insert into test values(NULL,'third'); -- ERR_NULL_COL_VALUE
insert into test overriding system value values(NULL, 'third'); -- ERR_NULL_COL_VALUE
insert into test overriding user value values(NULL, 'fourth'); -- valid query, id for this row will be 3
insert into test(name) values('fifth'); -- valid query, id from this row will be 4
select * from test;
drop table test;

