#################################################################
#								#
# Copyright (c) 2023 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

create table test (id int generated always as identity, name text);
create table test2 (id int generated by default as identity, name text);
create table test3 (id int , names text);
create table test4 (name text, id int generated always as identity);
create table test5 (name text, id int generated by default as identity);
\d test;
\d test2;
\d test3;
\d test4;
\d test5;
