#!/usr/bin/expect
#################################################################
#								#
# Copyright (c) 2021-2023 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

set timeout 60

# Start bash with --noprofile as otherwise SUSE /etc/profile blindly overwrites $PATH causing below "octo" invocations to fail
spawn /bin/bash --noprofile

expect -re "\[#\$] "
# Enable long lines to prevent wrapping
send -- "stty cols 4096\r"
expect -re "\[#\$] "

# Start octo
send -- "octo\r"
expect "OCTO> "

# Quit with Semicolon
send -- "QUIT;\r"
expect -re "\[#\$] "
