#!/usr/bin/expect
#################################################################
#								#
# Copyright (c) 2021-2023 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

set timeout 60

# Start bash with --noprofile as otherwise SUSE /etc/profile blindly overwrites $PATH causing below "octo" invocations to fail
spawn /bin/bash --noprofile

expect -re "\[#\$] "
# Enable long lines to prevent wrapping
send -- "stty cols 4096\r"
expect -re "\[#\$] "

# Start octo
send -- "octo\r"
expect "OCTO> "

# Single line query w/o semicolon
send -- "select * from names\r"
expect "OCTO> "

# Exit Octo using CTRL-D
send -- "\x04"
expect -exact "\r
id|firstname|lastname\r
0|Zero|Cool\r
1|Acid|Burn\r
2|Cereal|Killer\r
3|Lord|Nikon\r
4|Joey|\r
5|Zero|Cool\r
(6 rows)\r"
expect -re "\[#\$] "
