#!/usr/bin/expect
#################################################################
#								#
# Copyright (c) 2021-2022 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

set timeout 60
spawn /bin/bash
expect -re "\[#\$] "
# Enable long lines to prevent wrapping
send -- "stty cols 4096\r"
expect "stty cols 4096\r"

# Start octo
send -- "octo\r"
expect "OCTO> "

# History
send -- "\\s\r"
expect "OCTO> "

# Exit Octo using CTRL-D
send -- "\x04"
expect -re "\[#\$] "
