#################################################################
#								#
# Copyright (c) 2021 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

-- TTA006 : OCTO759 : TABLENAME.ASTERISK produces incorrect results when used with ORDER BY and LEFT JOIN : nullnames database

-- Below are queries from https://gitlab.com/YottaDB/DBMS/YDBOcto/-/issues/759#note_736104049 using the "nullnames" database
-- These are fancier queries generated by the TQG06 subtest that fail due to YDBOcto#759.
SELECT ALL alias3.exempt, alias1.* FROM nullnamesb  LEFT JOIN (SELECT alias1.lastName FROM nullnamesb alias1 ORDER BY alias1.lastName) AS alias1 ON (((nullnamesb.lastName IS NOT NULL)) AND ((nullnamesb.firstName IS NOT NULL) AND NOT (nullnamesb.firstName IS NULL))) CROSS JOIN nullnamesb AS alias3 WHERE (('Cereal'||'Zero') IS NOT NULL) ORDER BY alias1.*, alias3.exempt;
SELECT ALL alias5.exempt, alias1.* FROM nullnamesb  LEFT OUTER JOIN (SELECT ALL alias1.lastName FROM nullnamesb alias1 WHERE ((alias1.yearsTenured IS NOT NULL)) ORDER BY alias1.lastName) AS alias1 ON ((nullnamesb.lastName IS NOT NULL) OR NOT ((nullnamesb.salary IS NOT NULL)) AND ((nullnamesb.firstName IS NULL))) INNER JOIN (SELECT ALL alias5.exempt, alias5.lastName FROM nullnames alias5 WHERE alias5.exempt BETWEEN 0::boolean AND 1::boolean ORDER BY alias5.exempt, alias5.lastName) AS alias5 ON ((nullnamesb.exempt IS NOT NULL) OR NOT ((nullnamesb.exempt IS NOT NULL)) OR (nullnamesb.exempt IS NULL)) ORDER BY alias1.*, alias5.exempt;
SELECT ALL alias3.salary, alias1.* FROM nullnamesb  LEFT OUTER JOIN (SELECT alias1.lastName FROM nullnamesb alias1 ORDER BY alias1.lastName) AS alias1 ON (((nullnamesb.lastName IS NOT NULL))) CROSS JOIN (SELECT ALL alias3.exempt, alias3.salary FROM nullnames alias3 ORDER BY alias3.exempt, alias3.salary) AS alias3 WHERE ((nullnamesb.yearsTenured-0)=0) ORDER BY alias1.*, alias3.salary;

